#!/bin/sh

set -e

lb config noauto \
        -b netboot \
        --architecture amd64 \
        --distribution jessie \
        --net-root-path "/nfsroot/debianlive" \
        --net-root-server "192.168.2.4" \
        --bootappend-live "locale=de_DE.UTF-8 keyboard-layouts=de" \

	"${@}"
